### ISSUE TITLE
hard to debug firmware.c with no stack trace

### ISSUE THREAD

**Issue by bennlich** [sudomesh/disaster-radio-simulator#10]
been working a bit with @paidforby today and the firmware will occasionally crash with no useful info :-/

Maybe implementing some of these things will help debug: https://spin.atomicobject.com/2013/01/13/exceptions-stack-traces-c/

**Comment by paidforby** [comment]
See recent commit where I added [backward-cpp](https://github.com/bombela/backward-cpp). It currently provides a minimal stack trace, but I think it can be tricked out further. 

Recently, I've really liked using vim's built-in termdebug feature for debugging. See this informative article for more about termdebug, https://www.dannyadam.com/blog/2019/05/debugging-in-vim/
