### ISSUE TITLE
Arduino.h not found

### ISSUE THREAD

**Issue by Lithimlin** [sudomesh/disaster-radio-simulator#14]
This is gonna be a quick one:

Do I need to intall this in some kind of arduino folder? I tried cloning it and compiling the firmware, but the `Arduino.h` could not be found. I have arduino installed, but I didn't clone the simulator in any of its directories.

**Comment by paidforby** [comment]
After running `./fetch_deps` you need to comment [line 11](https://github.com/sudomesh/LoRaLayer2/blob/master/src/Layer1.h#L11)  and uncomment line 12 in `routers/libs/LoRaLayer2/src/Layer1.h`. I'll add these instructions to the README.

Sorry about that, the portability isn't that well designed and I haven't been developing the simulator very much recently. Let me know if you find any other bugs.

**Comment by paidforby** [comment]
I've fully fixed this by adding a `-DSIM` flag to the Makefile along with some other changes to how the Layer1 source files are chosen.
