### ISSUE TITLE
use same emojis for retransmitted packets + sync viz animation timings to actual sim timings

### ISSUE THREAD

**Issue by paidforby** [sudomesh/disaster-radio-simulator#6]
in latest commit 1500d5f77a629634451fbc7da8b000afef6305f0 retransmitting should occur after the learning phase is complete (assuming the network is well-constructed, i.e. it has some two-hop routes). Visually, it is difficult to tell when a packet is retransmitted because the retransmit gets triggered immediately after the initial transmit, such that the animations are out of sync. Additionally, it would be nice if the emoji for the retransmitted packet was the same as the emoji for the initial packet. Is this feasible @bennlich ? Right now, the data in the initial and retransmitted packets are identical, so you should be able to tie the emoji to the data in the packets.

**Comment by bennlich** [comment]
Have a look at https://github.com/sudomesh/disaster-radio-simulator/commit/86f841031da5127618d7f9398921f3b97b88cc80 and https://github.com/sudomesh/disaster-radio-simulator/commit/c9fe54d93edacc2b1659993b25ae003bd8a4736b.

The first commit makes the viz run at the same speed as the simulator, and also adds an option to the Network class for slowing down time. I set the default to 10x slower.

The second commit is an attempt at making the retransmit emoji the same as the initial packet emoji. I think the logic is right, but I'm not sure I'm parsing the packet data correctly. Does the [parsePacket](https://github.com/sudomesh/disaster-radio-simulator/commit/c9fe54d93edacc2b1659993b25ae003bd8a4736b#diff-63f3aa32c5cc5d42a250b081693e9dc2) function look right to you? You can inspect the `emojiCache` from the javascript console if you want to see what packet data the viz is associating with each emoji.

**Comment by paidforby** [comment]
It appears to work correctly, though I would suggest to cache the emoji by the entire packet (i.e. header+data), not just the data in the packet. This way the packet will change every time except on retransmit because the sequence number changes on every initial transmit, but every retransmit is the exact same packet, though this could change very soon depending on how we implement multi-hop routing.

**Comment by paidforby** [comment]
@bennlich the time distortion added by 86f841031da5127618d7f9398921f3b97b88cc80 drastically effects neighbor/route discovery. I think applying the distortion to the airtime delay is a bad idea because that is tied to other aspects of the simulator that determine if a node can receive a packet. Initially, I thought to slow down the airtime as well, I'm having trouble thinking of a better way to distort the animation and still keep it in sync with the simulator. For development purposes, I'm ok using a time distortion of 1 and with 1857b5adb244ef732988c025be22c1db690459a2 it much more bearable to debug by console output.

**Comment by paidforby** [comment]
I think I came up with best solution. Somewhat counter-intuitively, we actually want the airtime delay to be smaller such that the we can run the simulator faster (right now it takes more than two minutes for a 15 node network to converge). More importantly, we need to reimplement the message buffer in the firmware, which I had neglected for some time. This will prevent a retransmit from occurring immediately and instead wait 3-5s to retransmit. Then we can make the animation 10 times slower than the actual airtime which is usually (200ms-1s).
Maybe we could eventually the buffer delay a factor of the airtime of the packet, though that would require calculating the airtime in the C code.

**Comment by bennlich** [comment]
> I think I came up with best solution. Somewhat counter-intuitively, we actually want the airtime delay to be smaller such that the we can run the simulator faster (right now it takes more than two minutes for a 15 node network to converge).

Interesting. In this case, convergence means every node has its own complete copy of the routing table to every other reachable node? Any idea why it takes so long to converge? I think my (naive) guess for convergence time would be `(time to transmit one message + delay between sending subsequent messages) * (network width) * 2`. I'm thinking this would be the time to get a message from one end of the network to the opposite end and back again.

Actually maybe this is a good estimate--for 15 nodes, lets say the network width is ~7 links. Then:
```
(time to transmit one message + delay between sending subsequent messages) * (network width) * 2
= (0.2 + 10) * (7) * 2 = 142.8s
```

Pretty close to the reported "more than two minutes"!

---

Does the hello phase need to be separate from the route discovery phase? If so, does it need to last 40 seconds? Instead could the hello phase end once every node emits its "hello" once (i.e. after ~2s)?

---

> More importantly, we need to reimplement the message buffer in the firmware, which I had neglected for some time. This will prevent a retransmit from occurring immediately and instead wait 3-5s to retransmit.

Hmmm. Why would you not want to retransmit immediately (besides for viz purposes)?

> Maybe we could eventually [make] the buffer delay a factor of the airtime of the packet.

I don't understand the purpose of the buffer delay :-/

**Comment by bennlich** [comment]
> Somewhat counter-intuitively, we actually want the airtime delay to be smaller such that the we can run the simulator faster

Ah, right. Makes sense. I see two options:
1) Make the simulator run at a fixed time (cannot change sim playback speed). Make the viz buffer all messages it receives, and make it able to play back those messages at an arbitrary, adjustable "viz time".
2) Make the viz always playback at simulator time. Whatever you see in the viz is what is happening in the simulator. Make the simulator playback time adjustable.

I'm leaning pretty heavily towards 2. It seems a little harder to implement because you have to make changes to simulator.js and the firmware code, but it seems like a much simpler mental model than having two clocks--a viz clock and a simulation clock.

I also think the whole point of the viz is to help you understand what is really going on in the simulator, and having a different clock than the simulator does not seem in line with that goal to me.

**Comment by paidforby** [comment]
I documented some thoughts regarding the different stages of a node joining a network (you might have already seen) [here](https://github.com/sudomesh/disaster-radio/wiki/Protocol#node-states). You are correct that the differentiation between the hello/discovery phase and route-sharing/learning phase is not necessary. Hello packets are essentially empty routing packets, though I do like the idea of keeping hello packets as an option for a low transmit time update to neighbors (i.e. "hey I'm still alive" packets). I noticed that routing packets can become fairly heavy (i.e. long transmit times) once they contain more than 10 routes, I have yet to try a full 30 route packet.

> 2. Make the viz always playback at simulator time. Whatever you see in the viz is what is 
> happening in the simulator. Make the simulator playback time adjustable.
> 
> 
> I'm leaning pretty heavily towards 2.

I agree in leaning towards option two. It would be nice to have a slider or knob to control the playback of the simulator (both firmware and viz). But I wasn't sure how to even to start implementing this idea. 

As for the buffer delay, it is necessary so that the firmware does not attempt to load a message while it is still transmitting the previous message in the buffer (i.e. what if a node received two routed packet almost simultaneously?). In the firmware proper, this is handled by a TxDone interrupt bit sent from the LoRa transceiver, which determines the value `LoRa.beginPacket()` returns in [this line](https://github.com/sudomesh/disaster-radio/blob/master/firmware/firmware.ino#L655). We have yet to implement any such TxDone interrupt in the simulator, so the buffer delay approximates the time needed to send the largest possible packet.

**Comment by bennlich** [comment]
> Hello packets are essentially empty routing packets, though I do like the idea of keeping hello packets as an option for a low transmit time update to neighbors (i.e. "hey I'm still alive" packets). I noticed that routing packets can become fairly heavy (i.e. long transmit times) once they contain more than 10 routes, I have yet to try a full 30 route packet.

Ahhh, I see. This makes sense to me. Thanks.

> I agree in leaning towards option two. I would be nice to have a slider or knob to control the playback of the simulator (both firmware and viz). But I wasn't sure how to even to start implementing this idea.

Yeah that would be sweet. One tricky thing is that the C program would need to receive messages about changing its timings, but we're already using stdin for receiving packets... Maybe we could send some kind of simulation interrupt signal, then send configuration info, then send simulation resume.

> As for the buffer delay, it is necessary so that the firmware does not attempt to load a message while it is still transmitting the previous message in the buffer (i.e. what if a node received two routed packet almost simultaneously?). In the firmware proper, this is handled by a TxDone interrupt bit sent from the LoRa transceiver, which determines the value LoRa.beginPacket() returns in this line. We have yet to implement any such TxDone interrupt in the simulator, so the buffer delay approximates the time needed to send the largest possible packet.

Right--makes sense that a message buffer is required. What I'm understanding is that in the firmware proper there is no artificial buffer delay--the firmware just moves to the next message in its buffer as soon as it is not transmitting anything.

It seems like some of this interrupt logic is already implemented in the `node` file? I'm looking at:
https://github.com/sudomesh/disaster-radio-simulator/blob/master/node.js#L144-L151 and https://github.com/sudomesh/disaster-radio-simulator/blob/master/node.js#L191. Is this the stuff that needs to be reimplemented in the firmware?

**Comment by paidforby** [comment]
Yes, the transmitting interrupt is implemented in the `node` file, but it does not need to be reimplemented in the firmware, rather that value needs to be passed down to the firmware in somehow. 

You are correct that stdin is already occupied with handling packets, but I don't think we need to stop the simulation necessarily. It would be fairly easy to write a "special" metadata packet to stdin that is intended to be handled by `base.c` and not handed to `firmware.c` as an actual packet. 

This metadata packet could then be used to solve both simulator speed syncing and the transmitting interrupt problems. I'll look into modifying `node.js` and `base.c` to share the necessary metadata.

**Comment by paidforby** [comment]
Recent commit opens a world of possibilities. We can now post arbitrary metadata messages to the router, see my lazy example messages [here](https://github.com/sudomesh/disaster-radio-simulator/blob/master/node.js#L165), these are passed to `base.c` through stdin and parsed [like so](https://github.com/sudomesh/disaster-radio-simulator/blob/master/routers/base.c#L85). Adding additional cases to the switch statement would allow other configurations (such as simulation speed) to be controlled/shared between the firmware and viz.

**Comment by bennlich** [comment]
Sweet dealy!!! Part of me wants to stay up and implement a time slider in the UI. But part of me knows I'll end up slicing my fingers off in wood class tomorrow if I don't get enough sleep... :sleeping:

Am also thinking to add an option to the firmware that sets the time delay from the get-go. E.g. `./router/firmware -t 10`. Then future changes can come via the websocket.

**Comment by paidforby** [comment]
yeah, sleep is necessary, esp. when woodworking (learned that the hard way). But yes, an option in the firmware sounds like a good way to go, probably won't have much time today to work on this, but I can help integrate that feature into the firmware either late tonight or tomorrow.

**Comment by bennlich** [comment]
@paidforby see what you think of https://github.com/sudomesh/disaster-radio-simulator/commit/4ebd8f1c51fe7dcecf9a2ad307797b9fd2f0ef59 https://github.com/sudomesh/disaster-radio-simulator/commit/e90c6c929e347e81ccbc378295f1cc5bae07a375 https://github.com/sudomesh/disaster-radio-simulator/commit/3a0ab541bb161a5ba0517d8bb3e9976770cfcf38

**Comment by paidforby** [comment]
Awesome additions! Look like good changes to me. Now it should be easy to link changes in the time distortion to the firmware through metadata packets.

**Comment by paidforby** [comment]
hmm, so I'm thinking there is one small problem with this update. I think we also need to do something with the nsleep call in the firmware loop, https://github.com/sudomesh/disaster-radio-simulator/blob/master/routers/firmware.c#L716

**Comment by bennlich** [comment]
Ah, ya. Good call.

**Comment by paidforby** [comment]
changing it to `nsleep(0, 100*simulationTime(1))` appears to work

**Comment by bennlich** [comment]
hmmm. shouldn't it be `1000000*simulationTime(1)` ? If it's microseconds?

**Comment by paidforby** [comment]
good point, i was thinking milliseconds

**Comment by paidforby** [comment]
With our recent commits adding better control of animation speed and better keying of emojis, I'm going to consider this issue well beaten. I have some other ideas regarding animations, but will open a new issue for that. Thanks for all the back-and-forth @bennlich !!!

**Comment by bennlich** [comment]
🐴🌈
