### ISSUE TITLE
hello + messaging phases staggered by wait, but not discovery phase

### ISSUE THREAD

**Issue by bennlich** [sudomesh/disaster-radio-simulator#8]
I noticed that the hello messages don't get sent all at once, but the routing advertisements do get sent all at once. (After 30s, all nodes start firing at once.) Is this intentional? Or should we add:
```
_discoveryTimeout += wait;
```
to line 732 in firmware.c?

**Comment by paidforby** [comment]
yes we should, good catch, I bet that was effect the convergence of the network

**Comment by paidforby** [comment]
learning phase seems to work more smoothly now, I was wondering why it seemed like they all synced back up, thanks for point this out.
